FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /src
COPY NuGet.Config Binance.LocalOrderBook.sln ./
COPY src/Binance.LocalOrderBook/Binance.LocalOrderBook.csproj src/Binance.LocalOrderBook/
COPY tests/Binance.LocalOrderBook.Tests/Binance.LocalOrderBook.Tests.csproj tests/Binance.LocalOrderBook.Tests/
RUN dotnet restore Binance.LocalOrderBook.sln
COPY src/Binance.LocalOrderBook/*.cs src/Binance.LocalOrderBook/
COPY tests/Binance.LocalOrderBook.Tests/*.cs tests/Binance.LocalOrderBook.Tests/
RUN dotnet build Binance.LocalOrderBook.sln --configuration Release --no-restore -warnaserror
ENTRYPOINT ["/bin/sh", "-c", ": \"${TEST_FILTER:?TEST_FILTER is required}\"; exec dotnet test Binance.LocalOrderBook.sln --configuration Release --no-build --no-restore --logger 'console;verbosity=detailed' --filter \"$TEST_FILTER\""]
